### ISSUE TITLE
When make ulordrig, a error reported

### ISSUE THREAD

**Issue by yikongzi** [UlordChain/ulordrig#1]
$ make
[ 40%] Built target cryptoHello
[ 48%] Built target cpuid
Linking CXX executable ulordrig
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lstdc++
collect2: 错误：ld 返回 1
make[2]: *** [ulordrig] 错误 1
make[1]: *** [CMakeFiles/ulordrig.dir/all] 错误 2
make: *** [all] 错误 2

My Linux version
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

$ uname -a
Linux 192.168.1.189 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
--------------------------------
Walk around method :
In fact , ulordrig does not use lib  libssl and libstdc++.
In the last step , "Linking CXX executable ulordrig", if delete " -lssl "
and  "-static-stdc++" , the executable file ulordrig was created successfully.

**Comment by jxinhu** [comment]
The error may be the lack of library ssl and stdc++, -static-libstdc++ to specify static links, remove this parameter and automatically link to its dynamic library. -lssl can be removed.

**Comment by myaleon** [comment]
I have similar errors showing.

For stdc++ also could be simply solved by install libstdc++-static
