### ISSUE TITLE
Mining program stuck on upgrading or connecting in WIN10

### ISSUE THREAD

**Issue by Feitong-Hu** [UlordChain/ulordrig#10]
I met this issue on my two VMs, and the same issue reported by different people in WeChat "Ulord上海挖矿群“, Better to find why and solve it before the official chain is online. 

I tried mining on Win10 in 3 computers, succeed in one, but failed in other 2. 
The one instance I succeed to mine is running on a VM, but sharing the network of the host, which get network configuration via DHCP. 

The other 2 instances I run also in VMs, but the network is configured manually, only http/https proxies configured. The system has no problem to access external network via browsers (for both http and https). 

My instances are stuck on upgrading, keep running always. Nothing I could for it.

**Comment by taylorshuang** [comment]
You first let all VMs connect to the Internet.

**Comment by taylorshuang** [comment]
先让所有的虚拟机能上网，然后挖矿程序才能跑起来的。
