### ISSUE TITLE
CentOS 7安装库和程序的时候，到最后一步 # make installc出错

### ISSUE THREAD

**Issue by linkpjc** [UlordChain/ulordrig#11]
[dc2-user@10-255-0-72 libuv]$ make install
make[1]: Entering directory `/home/dc2-user/libuv'
 /bin/mkdir -p '/usr/local/lib'
 /bin/sh ./libtool   --mode=install /bin/install -c   libuv.la '/usr/local/lib'
libtool: install: /bin/install -c .libs/libuv.so.1.0.0 /usr/local/lib/libuv.so.1.0.0
/bin/install: cannot create regular file '/usr/local/lib/libuv.so.1.0.0': Permission denied
make[1]: *** [install-libLTLIBRARIES] Error 1
make[1]: Leaving directory `/home/dc2-user/libuv'
make: *** [install-am] Error 2

求指教

**Comment by jxinhu** [comment]
sudo make install
