### ISSUE TITLE
在centos7上启动遇到的lib版本不一致的问题

### ISSUE THREAD

**Issue by Disac** [UlordChain/ulordrig#12]
./Ulordrig: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

centos默认安装1.0.2k

这里一直用 libcrypto.so.1.0.0，很苦恼，而且libssl的包还不能乱改，不然ssh上不去了

**Comment by Disac** [comment]
如果添加软连接
ln -s libcrypto.so.1.0.2k libcrypto.so.1.0.0
会出现下面的错误
/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found

**Comment by jxinhu** [comment]
<https://github.com/UlordChain/ulordrig/releases>

**Comment by mirror222** [comment]
下载：https://www.openssl.org/source/old/1.0.1/openssl-1.0.1e.tar.gz
执行./config shared zlib-dynamic 来生成Makefile文件。
通过make来生成生成libssl.so.1.0.0和libcrypto.so.1.0.0
将这2个文件拷贝到cd /usr/lib64/，然后执行以下2条生成软连接解决。
ln -s libssl.so.1.0.0          libssl.so.10
ln -s libcrypto.so.1.0.0    libcrypto.so.10

**Comment by huxianer** [comment]
@mirror222 按照你的操作，结果ssh登不上了，这是为啥。。。

**Comment by mzhou2018** [comment]
> @mirror222 按照你的操作，结果ssh登不上了，这是为啥。。。

提示什么了？搜索 升级OPENSSL 后无法ssh

**Comment by huxianer** [comment]
@mzhou2018 提示“git-remote-https: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory” ，但是用sudo git clone 是可以的~

**Comment by mzhou2018** [comment]
> @mzhou2018 提示“git-remote-https: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory” ，但是用sudo git clone 是可以的~

可参考这个
https://blog.csdn.net/qq_30507287/article/details/69389982

**Comment by ghost** [comment]
> @mirror222 按照你的操作，结果ssh登不上了，这是为啥。。。

强烈在不懂的情况下不要乱修改，修改ssl的配置非常敏感，ssh依赖ssl，许多需要加密的软件都依赖。
我进行软链接ssh已经无法登录！
