### ISSUE TITLE
Ubuntu Build 命令不完整

### ISSUE THREAD

**Issue by 373137461** [UlordChain/ulordrig#15]
sudo apt install git build-essential gcc g++ cmake libuv1-dev libmicrohttpd-dev openssl

应该修改为

sudo apt install git build-essential gcc g++ cmake libuv1-dev libmicrohttpd-dev openssl  libssl-dev

否则报错

ulordrig/src/crypto/c_aes128.c:7:25: fatal error: openssl/md5.h: No such file or directory compilation terminated.

**Comment by jxinhu** [comment]
thanks

**Comment by PinkD** [comment]
然而时至今日，还没有改
