### ISSUE TITLE
confusing descriptions for the usage

### ISSUE THREAD

**Issue by yinchuandong** [UlordChain/ulordrig#16]
1. for the option``` -u```,  the demo shows ```./ulordrig -o stratum+tcp://main-pool.ulorders.com:18888 -u Uj2ubGNrCUmZ6ib6rs3Jrp9bz76zKAfYyq.main -p x -t 1```.
Note that there is a suffix ```.main``. Is it only for the example? Do I need to add ```.main``` for my wallet address?

2. for the option ```-p```,  should I replace the ```x``` in the demo with my wallet password. How to handle it if my wallet does not need a password?

3. Do you provide any other servers for mining? Where can I view all the server list?

**Comment by jxinhu** [comment]
`-u` :  username: <https://github.com/UlordChain/ulordrig/issues/5>    
 `-p` :  password for mining server
more options: <https://github.com/UlordChain/ulordrig#options>    
another pool server: <http://u1pool.com:8080/>

**Comment by yinchuandong** [comment]
Thanks for your responses. I have another question. What is the definition of the worker? For example, if I have two servers to run the mining program. Can I set the option ``` -u ``` with ``` wallet address + .server1 ``` and ``` wallet address + .server2``` for these two servers respectively?
What will happen if I use  the same ``` wallet address ``` for both servers? 

By the way, regarding the password of the mining server, even if I set a wrong password, the ``` ulordrig``` will still run. I wish it can throw an exception to remind developers.

**Comment by jxinhu** [comment]
We use worker to distinguish the different machines owned by one user,  it can be quickly found out when one machine stop mining.   Of course you can set  the same wallet address for more machines if you want.  What is the password of mining pool that is decided by the pool owner.  At present,  the password does not work in many mining pools.
