### ISSUE TITLE
正向代理设置

### ISSUE THREAD

**Issue by laopeng** [UlordChain/ulordrig#17]
我的电脑是通过设置代理服务器访问外网的，请问要怎么配置才能正常挖矿？

**Comment by jxinhu** [comment]
能正常访问矿池的挖矿端口即可

**Comment by laopeng** [comment]
像wget -e "http_proxy=10.1.4.43:8080"  proxy.mimvp.com
curl -x 10.1.4.43:8080 proxy.mimvp.com 都有代理设置，但是在ulordrig中不提供这样的方式，无法正常访问到挖矿端口。

**Comment by taylorshuang** [comment]
挖矿程序走的是TCP连接，若用代理的话，建议用Haproxy，很容易配置，也很稳定。
