### ISSUE TITLE
MAC下编译报错

### ISSUE THREAD

**Issue by niettcat** [UlordChain/ulordrig#18]
Mac版本：10.13.3 
错误信息如下：
Undefined symbols for architecture x86_64:
  "_sha3_update", referenced from:
      _crypto_sha3_256 in libcryptoHello.a(c_sha3_256.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chaoukis** [comment]
@niettcat Hey could you tell me how you fixed this issue. I am currently having the same issue when building my iOS app
