### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by myaleon** [UlordChain/ulordrig#2]
A document issue:

sudo apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev    
git clone https://github.com/UlordChain/ulordrig.git   
cd ulordrig     
make build && cd build      <<---< looks like have to be changed to "mkdir build && cd build"
cmake ..    
make

**Comment by taylorshuang** [comment]
ok , we will modify this error, thanks.

**Comment by jxinhu** [comment]
It has been modified. thanks
