### ISSUE TITLE
Which pools can I mine on?

### ISSUE THREAD

**Issue by Jedshady** [UlordChain/ulordrig#21]
I have tried to mine on several pools.
It may have different hashrate on different pools due to the network etc. I suppose.
I found that I can achieve best hashrate on pool 222.187.239.238. Is this pool a main pool or just for test? Are the coins mined on this pool able to converted to real UT? 
If it is just for test, could you provide a list of all main pools I may use.
Thank you

**Comment by jxinhu** [comment]
Maybe you can think about it: <http://u1pool.com:8080/>
