### ISSUE TITLE
CentOS  7.5 上面，编译到最后，链接的时候，报错，好多的函数没有定义。

### ISSUE THREAD

**Issue by yikongzi** [UlordChain/ulordrig#23]
/usr/bin/c++    -Wall -fno-exceptions -fno-rtti -maes -std=c++11  -O0 -Wall -g -ggdb    -static-libgcc -static-libstdc++ CMakeFiles/ulordrig.dir/src/api/Api.cpp.o CMakeFiles/ulordrig.dir/src/api/ApiState.cpp.o CMakeFiles/ulordrig.dir/src/api/NetworkState.cpp.o CMakeFiles/ulordrig.dir/src/App.cpp.o CMakeFiles/ulordrig.dir/src/Console.cpp.o CMakeFiles/ulordrig.dir/src/log/ConsoleLog.cpp.o CMakeFiles/ulordrig.dir/src/log/FileLog.cpp.o CMakeFiles/ulordrig.dir/src/log/Log.cpp.o CMakeFiles/ulordrig.dir/src/Mem.cpp.o CMakeFiles/ulordrig.dir/src/net/Client.cpp.o CMakeFiles/ulordrig.dir/src/net/Job.cpp.o CMakeFiles/ulordrig.dir/src/net/Network.cpp.o CMakeFiles/ulordrig.dir/src/net/strategies/DonateStrategy.cpp.o CMakeFiles/ulordrig.dir/src/net/strategies/FailoverStrategy.cpp.o CMakeFiles/ulordrig.dir/src/net/strategies/SinglePoolStrategy.cpp.o CMakeFiles/ulordrig.dir/src/net/SubmitResult.cpp.o CMakeFiles/ulordrig.dir/src/net/Url.cpp.o CMakeFiles/ulordrig.dir/src/Options.cpp.o CMakeFiles/ulordrig.dir/src/Platform.cpp.o CMakeFiles/ulordrig.dir/src/Summary.cpp.o CMakeFiles/ulordrig.dir/src/workers/DoubleWorker.cpp.o CMakeFiles/ulordrig.dir/src/workers/Handle.cpp.o CMakeFiles/ulordrig.dir/src/workers/Hashrate.cpp.o CMakeFiles/ulordrig.dir/src/workers/SingleWorker.cpp.o CMakeFiles/ulordrig.dir/src/workers/Worker.cpp.o CMakeFiles/ulordrig.dir/src/workers/Workers.cpp.o CMakeFiles/ulordrig.dir/src/ulordrig.cpp.o CMakeFiles/ulordrig.dir/src/App_unix.cpp.o CMakeFiles/ulordrig.dir/src/Cpu_unix.cpp.o CMakeFiles/ulordrig.dir/src/Mem_unix.cpp.o CMakeFiles/ulordrig.dir/src/Platform_unix.cpp.o CMakeFiles/ulordrig.dir/src/Cpu.cpp.o CMakeFiles/ulordrig.dir/src/log/SysLog.cpp.o  -o ulordrig -rdynamic /usr/local/lib/libuv.a -lpthread -lrt src/crypto/libcryptoHello.a src/3rdparty/libcpuid/libcpuid.a -lcrypto 
src/crypto/libcryptoHello.a(c_sha3_256.c.o)：在函数‘crypto_sha3_256’中：
/home/flylong/compile/ulordrig/src/crypto/c_sha3_256.c:14：对‘sha3_init’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/c_sha3_256.c:15：对‘sha3_update’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/c_sha3_256.c:16：对‘sha3_final’未定义的引用
src/crypto/libcryptoHello.a(PoW.c.o)：在函数‘initWorkMemory’中：
/home/flylong/compile/ulordrig/src/crypto/PoW.c:41：对‘my_rand64_r’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:50：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:51：对‘rrs’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:59：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:61：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:64：对‘rrs’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:67：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:68：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:69：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:70：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:72：对‘my_seed48_r’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:73：对‘my_seed48_r’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:74：对‘my_seed48_r’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:75：对‘my_seed48_r’未定义的引用
src/crypto/libcryptoHello.a(PoW.c.o)：在函数‘modifyWorkMemory’中：
/home/flylong/compile/ulordrig/src/crypto/PoW.c:97：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:102：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:105：对‘my_seed48_r’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:110：对‘my_rand48_r’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:114：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:132：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:135：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:139：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:142：对‘rrs’未定义的引用
src/crypto/libcryptoHello.a(PoW.c.o)：在函数‘calculateFinalResult’中：
/home/flylong/compile/ulordrig/src/crypto/PoW.c:165：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:168：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:180：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:182：对‘rrs’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:189：对‘reduce_bit’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:191：对‘rrs’未定义的引用
src/crypto/libcryptoHello.a(PoW.c.o)：在函数‘powNistTest’中：
/home/flylong/compile/ulordrig/src/crypto/PoW.c:315：对‘powFunction’未定义的引用
/home/flylong/compile/ulordrig/src/crypto/PoW.c:320：对‘powFunction’未定义的引用
src/crypto/libcryptoHello.a(c_ripemd160.c.o)：在函数‘crypto_ripemd160’中：
/home/flylong/compile/ulordrig/src/crypto/c_ripemd160.c:24：对‘reduce_bit’未定义的引用
src/crypto/libcryptoHello.a(c_sha1.c.o)：在函数‘crypto_sha1’中：
/home/flylong/compile/ulordrig/src/crypto/c_sha1.c:25：对‘reduce_bit’未定义的引用文件
src/crypto/libcryptoHello.a(c_sha512.c.o)：在函数‘crypto_sha512’中：
/home/flylong/compile/ulordrig/src/crypto/c_sha512.c:17：对‘reduce_bit’未定义的引用
src/crypto/libcryptoHello.a(c_whirlpool.c.o)：在函数‘crypto_whirlpool’中：
/home/flylong/compile/ulordrig/src/crypto/c_whirlpool.c:17：对‘reduce_bit’未定义的引用

这些报错，没有定义的函数，都是之间写在 .h  文件中的。 而这些 .h 文件中的函数，并没有编译进入目标文件。
是不是 cmake 的配置文件，在CentOS 7 上面不全面？

**Comment by jxinhu** [comment]
列出详细编译环境和过程

**Comment by yikongzi** [comment]
编译环境，应当就是 CentOS Linux release 7.5.1804 (Core) 自带的那些软件版本。

**Comment by yikongzi** [comment]
$ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux

**Comment by yikongzi** [comment]
有一个关键的因素，也许是带了调试信息编译， 比如编译选项 -g -O0

**Comment by yikongzi** [comment]
后来找到了解决办法。 根本原因是 C99 标准， 和 gcc 用的gnu 标准，在 处理 inline 函数是不一样的。
解决方法是添加 extern 申明。
所以，在用inline 函数的时候，要小心。 在不同的环境下，编译的结果可能不一样。

**Comment by yikongzi** [comment]
重要
C99标准中的inline函数行为定义的比较模糊，并且inline函数有没有在文件范围内被声明为extern的其表现有本质不同。如果和gcc的inline函数比较的话，一个被声明为extern的inline函数基本等价于GCC的普通inline函数；而一个没有被声明为extern的inline函数基本等价于GCC的extern inline函数。
因为C99的inline函数如此古怪，所以在使用的时候，建议为所有的inline函数都在头文件中创建extern的声明：
foo.h:

extern foo();
而在定义inline函数的c文件内include这个头文件：
foo.c:
#include "foo.h"
inline void foo()
{
    ...;
}
这样无论是用gcc的inline规则还是C99的，都能得到完全相同的结果：foo函数会在foo.c文件内被内联使用，而在外部又可以像普通全局函数一样直接调用。

**Comment by jxinhu** [comment]
Good job!
