### ISSUE TITLE
centos不会验证非法矿机编号

### ISSUE THREAD

**Issue by AsherHuu** [UlordChain/ulordrig#26]
linux挖矿程序ubuntu通过config配置文件可以验证矿机非法字符，而为什么centos的config并不会验证非法字符，但是命令行会，还有就是矿池1掉线了，会跳到设置的矿池2，矿池一好了但是并不会再次跳到矿池2去

**Comment by jxinhu** [comment]
We are going to fix it.

**Comment by coolhty** [comment]
为啥把下划线和减号也屏蔽了，要用来区分矿场、机柜的呢。

**Comment by taylorshuang** [comment]
@jxinhu 恩，需要把约束放宽点，增加下划线，便于区分矿场和机柜

**Comment by jxinhu** [comment]
在[v1.2.1](https://github.com/UlordChain/ulordrig/releases/tag/v1.2.1)修复了使用config.json时的非法字符验证，矿机编号允许包含下划线
