### ISSUE TITLE
How to set my ulord address?

### ISSUE THREAD

**Issue by yinhaibo** [UlordChain/ulordrig#5]
I found there is a command parameter to set user name and password for miner server. I don't know how to set my ulord address?

Thanks?

**Comment by jxinhu** [comment]
the username is made up of the wallet address and worker's name，separated  by ` . `  ，such as `-u uTRHNH71eiW2KMc2rSwmanpXGgDeKMZXdW.worker1 ` ,  worker's name can be omitted.

**Comment by yinhaibo** [comment]
aha, I got it.
