### ISSUE TITLE
cmake fail

### ISSUE THREAD

**Issue by hjiang0703** [UlordChain/ulordrig#6]
Hi,
When some error appears when I try to compile. Could you help me? 
BTW， I have installed libuv. Shoud I modify "FindUV.cmake" ?

[hochy@iz2ze1lflsecblvgr85cdoz ulordrig]$ cd build/
[hochy@iz2ze1lflsecblvgr85cdoz build]$ cmake .. 
.........
-- Detecting CXX compiler ABI info - done
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:130 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/hochy/ulordrig/build/CMakeFiles/CMakeOutput.log".

**Comment by jxinhu** [comment]
try this instead:   ` cmake  -DULORDRIG_DEPS="your uv library path" ..`
