### ISSUE TITLE
CentOS环境下，无法进行挖矿，开在# cd /var/tmp/ulordrig/build/CMakeFiles/ulordrig.dir 这步

### ISSUE THREAD

**Issue by hozyu12** [UlordChain/ulordrig#7]
CentOS环境下，无法进行挖矿，卡在# cd /var/tmp/ulordrig/build/CMakeFiles/ulordrig.dir
CentOS7的系统，进行到：
    # cd /var/tmp/ulordrig/build/CMakeFiles/ulordrig.dir
的时候，显示没有"ulordrig.dir"这个文件：
              -bash: cd: makefiles:No such file or directoy
我通过CMakeFiles目录ls查了一下确实没有这个文件，显示为：
[hozyu@ localhost ulordrig]$ cd build
[hozyu@ loca lhost build]$ Is
Cmakecache. txt Cmakefiles
[hozyue loca lhost build]$ cd CMakeFiles
[hozyuqloca lhost CMakefiles]$ ls
Z8. 12.2 cmake.check_cache Cmakeoutput log Cmake Tmp
然后好像从官方下克隆的时候，也就是 # git clone https://github.com/UlordChain/ulordrig.git
的时候，好像发现克隆不完全。
记录里显示： # git clone https://github.com/UlordChain/ulordrig.git
Cloning into 'ulordrig' ...
remote: Counting objects:536,done
remote: Compressing objects:100% (333/333),done.
remote: Total 536 (delta 325), reused 401 (delta 201), pack-reused 0
Resoiving objects:  100% (536/536), 375.04 kiB | 269.00 KiB/s, done
Resolving deltas:  100% (325/325), done.
我试了一个晚上了，包括重装系统还有删除所有文件再重新编译克隆，都没有用。
 # cd /var/tmp/ulordrig/build/CMakeFiles/ulordrig.dir
接着会显示：-bash: cd: makefiles:No such file or directoy
还有就是执行CentOS 7安装库和程序的时候，到最后一步 # make install
会在执行完出现：
Command line error : no such option: -D

**Comment by jxinhu** [comment]
你好，CentOS版本的ulordrig编译步骤已给出，请移步: <https://github.com/UlordChain/ulordrig/wiki/CentOS>

**Comment by hozyu12** [comment]
你好，我按着编译步骤走的，到了“# cd /var/tmp/ulordrig/build/CMakeFiles/ulordrig.dir”
回车以后提示
“-bash: cd: makefiles:No such file or directoy”

**Comment by jxinhu** [comment]
删掉旧文件夹重新安装：   https://github.com/UlordChain/ulordrig/wiki/CentOS

**Comment by jxinhu** [comment]
删掉旧文件夹按此步骤重新安装：  https://github.com/UlordChain/ulordrig/wiki/CentOS

**Comment by hozyu12** [comment]
在安装编译的时候，按着步骤走，执行“make install”的时候报错，记录如下：
[hozyu@localhost libuv]$ make install
make[1]: Entering directory '/var/tmp/libuv
    /bin/mkdir -p'/usr/local/lib'
   /bin/sh ./libtool    --mode=install /bin/install  -c  libuv. la'/usr/local/lib'
libtool: install: /bin/install -c  .libs/libuv.so.1.0.0 /usr/local/lib/libuv.so.1.0.0
/bin/install: cannot create regular file/usr/local/lib/libuvso 1.0.0': Permission denied
make[1]: *** [install-libLTL IBRARIES Error 1
make[1]: Leaving directory '/var/tmp/libuv
make: a [install-am] Error 2

**Comment by jxinhu** [comment]
sudo make install

**Comment by hozyu12** [comment]
编译文件跟步骤的不一样，帮看看。
[hozyu@locahost build]$ ls -Itr
total 828
drwrxrur-x. 4 hozyu hozyu         36May 15 17:25src
-rw-rw-r--. 1 hozyu hozyu  13091 May 15 17: 25 Cmakecache txt
-rw-rw-r--. 1 hozyu hozyu  34022 May 15 17: 25 Makefile
-rw-rw-r--. 1 hozyu hozyu    1852 May 15 17: 25 cmake_install. Cmake
-rwxrwxr-x. 1 hozyu hozyu  78774 May 15 17:28 ulordrig
drwxrwxr-x. 5 hozyu hozyu     235 May 15 17: 28 Cmakefiles
[hozyu@loca lhost build]$

**Comment by jxinhu** [comment]
官方没有展示编译文件，直接按用法运行程序 <https://github.com/UlordChain/ulordrig#usage>
