### ISSUE TITLE
ulordrig does not really mine in centos7

### ISSUE THREAD

**Issue by Feitong-Hu** [UlordChain/ulordrig#8]
I had git clone the source to my centos7.5 system, and make successfully after installed libmicrohttpd and libuv packages. 

However, when I run ulordrig with a config.json file, the program looks running, but actually not. I always see the CPU usage is very small (about 0.3%), and the second day I did not see any ULD mined in my wallet. 

```
[root@pop build]# cat config.json
{
	"algo": "cryptohello",
	"av": 0,
	"background": true,
	"colors": true,
	"cpu-affinity": "0xd",
	"cpu-priority": 4,
	"log-file": "./ulordrig.log",
	"max-cpu-usage": 75,
	"print-time": 60,
	"retries": 5,
	"retry-pause": 3,
	"safe": false,
	"syslog": false,
	"threads": 8,
	"pools": [
		{
			"url": "testnet-pool.ulord.one:7200",
			"user": "ufxMcopjrXvf8sbYKLjyLUEAAgGvShtx1Q",
			"pass": "x",
			"keepalive": true,
			"nicehash": false,
			"variant": -1
		}
	],
	"api": {
		"port": 0,
		"access-token": null,
		"worker-id": null
	}
}

```

```
[root@pop build]# head -15 ulordrig.log
[2018-05-13 02:47:16]  * VERSIONS:     ulordrig/1.0.0 libuv/1.20.4-dev gcc/4.8.5
[2018-05-13 02:47:16]  * CPU:          Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz (2) x64 AES-NI
[2018-05-13 02:47:16]  * CPU L2/L3:    8.0 MB/40.0 MB
[2018-05-13 02:47:16]  * THREADS:      8, cryptohello , affinity=0xD
[2018-05-13 02:47:16]  * POOL #1:      testnet-pool.ulord.one:7200
[2018-05-13 02:47:16]  * COMMANDS:     'h' hashrate, 'p' pause, 'r' resume
[2018-05-13 02:47:16]  * HUGE PAGES:   available, disabled
[2018-05-13 02:48:20] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-05-13 02:49:20] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-05-13 02:49:24] [testnet-pool.ulord.one:7200] connect error: "connection timed out"
[2018-05-13 02:50:20] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-05-13 02:51:20] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-05-13 02:51:35] [testnet-pool.ulord.one:7200] connect error: "connection timed out"
[2018-05-13 02:52:20] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-05-13 02:53:20] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s

```

```
[root@pop build]# ps aux | grep ulord
root      8914  0.0  0.0 814564  4476 ?        Ssl  02:40   0:00 ./ulordrig
root      8937  0.0  0.0 112704   972 pts/0    S+   02:41   0:00 grep --color=auto ulord
[root@pop build]# ps -p 8914 -o %cpu,%mem
%CPU %MEM
 0.0  0.0
[root@pop build]# ps -p 8914 -o %cpu,%mem
%CPU %MEM
 0.1  0.0

```

**Comment by Feitong-Hu** [comment]
Exactly the same issue happened in Ubuntu 16.4 environment. It might be configuration issue or my network issue. 

I am running this in an internal network with http/https proxy, but no sock proxy. It is related?

**Comment by jxinhu** [comment]
try:   "url" : "test-pool.ulord.one:7200"

**Comment by Feitong-Hu** [comment]
No use. 
Tried change testnet-pool.ulord.one:7200 to test-pool.ulord.one:7200, but the result is the same. 

Please help check the config.json (I added the .txt as extension name since github does not allow .json uploading) and the log file. 

[config.json.txt](https://github.com/UlordChain/ulordrig/files/2000170/config.json.txt)
[ulordrig.log](https://github.com/UlordChain/ulordrig/files/2000171/ulordrig.log)

Is it possibly related to my computer type? I am using a blade with 2 CPUs, 16 cores for each.

**Comment by jxinhu** [comment]
set "background" to false

**Comment by Feitong-Hu** [comment]
Actually I tried this, to make sure, just now I tested with "background"= false again, nothing changed except that the program is running foreground. It's strange.

**Comment by jxinhu** [comment]
I run successfully with your configuration on CentOS 7，  are you sure it's valid of your network?  test it with `telnet test-pool.ulord.one 7200` , if right, run ulordrig by command  `./ulordrig -o stratum+tcp://test-pool.ulord.one:7200 -u uTRHNH71eiW2KMc2rSwmanpXGgDeKMZXdW.worker -p x -t 1`

**Comment by taylorshuang** [comment]
I suppose add compilation steps of centos 7 in readme.

**Comment by jxinhu** [comment]
@taylorshuang  it has been linked in the  README which named [ Build instructions](https://github.com/UlordChain/ulordrig/wiki/Build), actualy, it's similar to Ubuntu's

**Comment by taylorshuang** [comment]
@jxinhu Good！I see it.

**Comment by Feitong-Hu** [comment]
@jxinhu, as I mentioned, I only have http/https proxy, no socks proxy. I got this: 

```
[root@pop ~]# telnet test-pool.ulord.one 7200
Trying 18.221.153.180...
telnet: connect to address 18.221.153.180: No route to host
[root@pop ~]#
[root@pop ~]# telnet test-pool.ulord.one 80
Trying 18.221.153.180...
Connected to test-pool.ulord.one.
Escape character is '^]'.
```
I would think this command requires socks proxy, since it does not communicate via http or https. So the question is: **does ulordrig require socks proxy from an internal network?**. If so, that would be really bad news for me, and for users who only have network as mine. 

I would suggest we enhance this to use REST API, then it will support more miners. 

Would you please confirm? 
In addition, does the  request for both windows and Linux system?

**Comment by taylorshuang** [comment]
@Feitong-Hu I know this problem, 80 port is web service, and on other server, i let them add a route to port 7200.

**Comment by Feitong-Hu** [comment]
@jxinhu @taylorshuang, thanks very much. 
I think we figure out the problem. So the question could be: could we use 80 port to connect the pool (instead of 7200), or, do you have a plan to set up a proxy for 80 to 7200 transferring?

**Comment by taylorshuang** [comment]
@Feitong-Hu There is no mining pool to provide mining services through the 80 port. When Mainnet is on line, we will move the mining pool to Ali cloud in Hongkong.

**Comment by taylorshuang** [comment]
@Feitong-Hu I would like to ask a question whether the servers in your internal network can connect to the Internet.

**Comment by taylorshuang** [comment]
When i execute  telnet test-pool.ulord.one 7200 in my server, i don‘t find your problem. In your environment, you only have one server to connect  to internet, and the other severs connect it to mining, is right? What  proxy software do you use?

**Comment by Feitong-Hu** [comment]
Yes. my server has no problem to connect to Internet via 80 port and 443 port, that is, only http and https, that's why 7200 could not be reached, I think.

**Comment by jxinhu** [comment]
Make the computer access some ports of the external network, such as 7200 used by ulord testnet for mining

**Comment by Feitong-Hu** [comment]
Solved via running via a OpenVPN to connect to the pool. The result is like this: 

```
[root@pop build]# ./ulordrig
 * VERSIONS:     ulordrig/1.0.0 libuv/1.20.4-dev gcc/4.8.5
 * HUGE PAGES:   available, disabled
 * CPU:          Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz (2) x64 AES-NI
 * CPU L2/L3:    8.0 MB/40.0 MB
 * THREADS:      8, cryptohello , affinity=0xD
 * POOL #1:      test-pool.ulord.one:7200
 * COMMANDS:     'h' hashrate, 'p' pause, 'r' resume
[2018-05-16 22:57:57] use pool test-pool.ulord.one:7200 18.221.153.180
[2018-05-16 22:57:57] new job from test-pool.ulord.one:7200 diff 3276
[2018-05-16 22:58:01] accepted (1/0) diff 3276 (257 ms)
[2018-05-16 22:58:04] accepted (2/0) diff 3276 (270 ms)
[2018-05-16 22:58:13] accepted (3/0) diff 3276 (251 ms)
[2018-05-16 22:58:21] accepted (4/0) diff 3276 (257 ms)
[2018-05-16 22:58:36] use pool test-pool.ulord.one:7200 18.221.153.180
[2018-05-16 22:58:36] new job from test-pool.ulord.one:7200 diff 3276
[2018-05-16 22:58:39] accepted (5/0) diff 3276 (253 ms)
[2018-05-16 22:58:47] accepted (6/0) diff 3276 (252 ms)
```

Appreciate your support! Move on. 
Please feel free to close this issue, I could support if anyone meet the similar issue.

**Comment by jxinhu** [comment]
Good， thanks！
